namespace ElvisCommand
{
    public enum HeatActionConditionType
    {
        Invalid = 0,
        CanAttackGeneric = 1,
        Down = 2,
        GettingUp = 3,
        CriticalHP = 4,
        Flinching = 5,
        Moving = 6,
        CharacterLevel = 7,
        AssetID = 8,
        WeaponType = 9,
        WeaponSubtype = 10,
        Distance = 11,
        DistanceToHactPosition = 12,
        Grabbing = 13,
        StageID = 14,
        JobLevel = 15,
        Job = 16,
        EXHeat = 17,
        FacingTarget = 18,
        Running = 19,
        BattleStance = 20,
        DistanceToNearestAsset = 21,
        NearestAssetSpecialType = 22,
        FacingRange = 23,
        DistanceToRange = 24,
        Attacking = 25,
        NearestAssetFlag = 26,
        DownOrGettingUp = 27,
        InRange = 28,
        IsBoss = 29,
        Health = 30,
        CtrlType = 31,
        SoldierID = 32,
        BattleConfigID = 33,
        WouldDieInHAct = 34,
        MotionID = 35,
        InBepElementRange = 36,
        BeingJuggled = 37,
        DownTime = 38,
        CurrentCommand = 39,
        IsSupporter = 40,
        SupporterFlags = 41,
        WeaponFlags = 42,
        HumanMode = 43,
        StatusEffect = 44,
        Swaying = 45,
        PlayerPoint = 46
    }
}
